server:
  port: 9082

spring:
  rabbitmq:
    host: 192.168.20.23
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        direct:
          binder: rabbit
          destination: p2p-topic
        broadcast:
          binder: rabbit
          destination: pubsub_topic



