server:
  port: 12100

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: signalout;signalin
    stream:
      bindings:
        signalin-in-0:
          destination: signal.topic
        signalout-out-0:
          destination: signal.topic
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin


