server:
  port: 12100

spring:
  rabbitmq:
    host: 192.168.20.23
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: signalout;signalin
    stream:
      bindings:
        signalin-in-0:
          destination: signal.topic
        signalout-out-0:
          destination: signal.topic
  r2dbc:
    url: r2dbc:postgresql://192.168.20.23:5432/postgres
    username: postgres
    password: admin


